### ISSUE TITLE
Add Windows support or mention that it's not supported

### ISSUE THREAD

**Issue by ricklamers** [harababurel/gcsf#17]
Coming from the HN post it wasn't clear to me that Windows wasn't supported. Given that Rust is cross platform it might be a good idea to mention this somewhere in the README.md.

You mentioned supporting it: 

Should be achievable using winfsp[0]. I will look into it for a future release.
[0] https://github.com/billziss-gh/winfsp

Possibly make an issue dedicated to it?

Cheers!

**Comment by harababurel** [comment]
I created a dedicated issue and added a note to the README page. Will close this issue and continue the discussion on #19.

**Comment by ricklamers** [comment]
Cool! Will keep an eye out

Op ma 2 jul. 2018 om 20:14 schreef Sergiu Puscas <notifications@github.com>:
