### ISSUE TITLE
Local vs. Cloud Storage?

### ISSUE THREAD

**Issue by alextechtai** [harababurel/gcsf#20]
Out of curiosity, does this take up local storage when mounted? If it does, is there a way to have some type of selective directories?

**Comment by harababurel** [comment]
It does not take up any local storage (unless you choose to manually copy files locally), but it can eat up RAM due to caching. This can be controlled by setting `cache_max_seconds` and `cache_max_items` in the configuration file.

**Comment by tjjh89017** [comment]
@harababurel There is a problem. Google will limit 750GiB uploading per day.
If gcsf cannot cache on local, there will be some problem when meet the limitation
