### ISSUE TITLE
Could not compile gcsf

### ISSUE THREAD

**Issue by sharnal** [harababurel/gcsf#21]
Hi,
I was trying to build gcsf and ran into the following error:

# cargo install gcsf
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading gcsf v0.1.7                                                        
  Installing gcsf v0.1.7                                                        
 Downloading id_tree v1.3.0
 Downloading serde_json v1.0.22                                                 
 Downloading rand v0.4.2                                                        
 Downloading google-drive3-fork v1.0.10                                         
 Downloading mime-sniffer v0.1.2                                                
 Downloading itertools v0.7.8                                                   
 Downloading ctrlc v3.1.1                                                       
 Downloading hyper-rustls v0.6.1                                                
 Downloading failure v0.1.1                                                     
 Downloading serde v1.0.69                                                      
 Downloading fuse v0.3.1                                                        
 Downloading pretty_env_logger v0.2.3                                           
 Downloading maplit v1.0.1                                                      
 Downloading log v0.4.3                                                         
 Downloading config v0.8.0                                                      
 Downloading lazy_static v1.0.1                                                 
 Downloading yup-oauth2 v1.0.7                                                  
 Downloading libc v0.2.42                                                       
 Downloading clap v2.32.0                                                       
 Downloading hyper v0.10.13                                                     
 Downloading time v0.1.40                                                       
 Downloading xdg v2.1.0                                                         
 Downloading lru_time_cache v0.8.0                                              
 Downloading chrono v0.4.4                                                      
 Downloading serde_derive v1.0.69                                               
 Downloading snowflake v1.3.0                                                   
 Downloading itoa v0.4.1                                                        
 Downloading dtoa v0.4.2                                                        
 Downloading url v0.5.10                                                        
 Downloading mime v0.2.6                                                        
 Downloading quote v0.6.3                                                       
 Downloading syn v0.14.4                                                        
 Downloading proc-macro2 v0.4.6                                                 
 Downloading unicode-xid v0.1.0                                                 
 Downloading log v0.3.9                                                         
 Downloading language-tags v0.2.2                                               
 Downloading base64 v0.6.0                                                      
 Downloading unicase v1.4.2                                                     
 Downloading url v1.7.0                                                         
 Downloading traitobject v0.1.0                                                 
 Downloading num_cpus v1.8.0                                                    
 Downloading typeable v0.1.2                                                    
 Downloading httparse v1.3.2                                                    
 Downloading cfg-if v0.1.4                                                      
 Downloading safemem v0.2.0                                                     
 Downloading byteorder v1.2.3                                                   
 Downloading version_check v0.1.3                                               
 Downloading idna v0.1.4                                                        
 Downloading matches v0.1.6                                                     
 Downloading percent-encoding v1.0.1                                            
 Downloading unicode-bidi v0.3.4                                                
 Downloading unicode-normalization v0.1.7                                       
 Downloading unicode-bidi v0.2.6                                                
 Downloading uuid v0.2.3                                                        
 Downloading rustc-serialize v0.3.24                                            
 Downloading rand v0.3.22                                                       
 Downloading rustls v0.9.0                                                      
 Downloading itertools v0.4.19                                                  
 Downloading base64 v0.5.2                                                      
 Downloading chrono v0.2.25                                                     
 Downloading ring v0.11.0                                                       
 Downloading untrusted v0.5.1                                                   
 Downloading webpki v0.14.0                                                     
 Downloading rayon v0.7.1                                                       
 Downloading gcc v0.3.54                                                        
 Downloading rayon-core v1.4.0                                                  
 Downloading crossbeam-deque v0.2.0                                             
 Downloading crossbeam-utils v0.2.2                                             
 Downloading crossbeam-epoch v0.3.1                                             
 Downloading scopeguard v0.3.3                                                  
 Downloading nodrop v0.1.12                                                     
 Downloading memoffset v0.2.1                                                   
 Downloading arrayvec v0.4.7                                                    
 Downloading webpki-roots v0.11.0                                               
 Downloading num v0.1.42                                                        
 Downloading num-integer v0.1.39                                                
 Downloading num-traits v0.2.5                                                  
 Downloading num-iter v0.1.37                                                   
 Downloading mime v0.3.8                                                        
 Downloading unicase v2.1.0                                                     
 Downloading either v1.5.0                                                      
 Downloading backtrace v0.3.9                                                   
 Downloading failure_derive v0.1.1                                              
 Downloading rustc-demangle v0.1.8                                              
 Downloading synstructure v0.6.1                                                
 Downloading quote v0.3.15                                                      
 Downloading syn v0.11.11                                                       
 Downloading synom v0.11.3                                                      
 Downloading unicode-xid v0.0.4                                                 
 Downloading thread-scoped v1.0.2                                               
 Downloading pkg-config v0.3.11                                                 
 Downloading env_logger v0.5.10                                                 
 Downloading ansi_term v0.11.0                                                  
 Downloading termcolor v0.3.6                                                   
 Downloading humantime v1.1.1                                                   
 Downloading atty v0.2.10                                                       
 Downloading regex v1.0.1                                                       
 Downloading quick-error v1.2.2                                                 
 Downloading memchr v2.0.1                                                      
 Downloading aho-corasick v0.6.5                                                
 Downloading utf8-ranges v1.0.0                                                 
 Downloading regex-syntax v0.6.1                                                
 Downloading thread_local v0.3.5                                                
 Downloading ucd-util v0.1.1                                                    
 Downloading unreachable v1.0.0                                                 
 Downloading void v1.0.2                                                        
 Downloading toml v0.4.6                                                        
 Downloading serde-hjson v0.8.1                                                 
 Downloading nom v3.2.1                                                         
 Downloading yaml-rust v0.4.0                                                   
 Downloading num-traits v0.1.43                                                 
 Downloading linked-hash-map v0.3.0                                             
 Downloading regex v0.1.80                                                      
 Downloading serde v0.8.23                                                      
 Downloading lazy_static v0.2.11                                                
 Downloading serde_test v0.8.23                                                 
 Downloading thread_local v0.2.7                                                
 Downloading regex-syntax v0.3.9                                                
 Downloading aho-corasick v0.5.3                                                
 Downloading utf8-ranges v0.1.3                                                 
 Downloading memchr v0.1.11                                                     
 Downloading thread-id v2.0.0                                                   
 Downloading kernel32-sys v0.2.2                                                
 Downloading winapi v0.2.8                                                      
 Downloading winapi-build v0.1.1                                                
 Downloading memchr v1.0.2                                                      
 Downloading linked-hash-map v0.5.1                                             
 Downloading unicode-width v0.1.5                                               
 Downloading bitflags v1.0.3                                                    
 Downloading yaml-rust v0.3.5                                                   
 Downloading vec_map v0.8.1                                                     
 Downloading strsim v0.7.0                                                      
 Downloading textwrap v0.10.0                                                   
 Downloading nix v0.11.0                                                        
 Downloading backtrace-sys v0.1.23                                              
 Downloading cc v1.0.17                                                         
   Compiling num-integer v0.1.39                                                
   Compiling utf8-ranges v0.1.3
   Compiling untrusted v0.5.1
   Compiling quick-error v1.2.2
   Compiling lru_time_cache v0.8.0
   Compiling regex-syntax v0.3.9
   Compiling byteorder v1.2.3
   Compiling matches v0.1.6
   Compiling quote v0.3.15
   Compiling cc v1.0.17
   Compiling nodrop v0.1.12
   Compiling unicode-xid v0.1.0
   Compiling serde v0.8.23
   Compiling memoffset v0.2.1
   Compiling unicode-xid v0.0.4
   Compiling vec_map v0.8.1
   Compiling itoa v0.4.1
   Compiling cfg-if v0.1.4
   Compiling rustc-serialize v0.3.24
   Compiling winapi v0.2.8
   Compiling safemem v0.2.0
   Compiling strsim v0.7.0
   Compiling rayon-core v1.4.0
   Compiling either v1.5.0
   Compiling itertools v0.4.19
   Compiling regex v1.0.1
   Compiling thread-scoped v1.0.2
   Compiling unicode-normalization v0.1.7
   Compiling winapi-build v0.1.1
   Compiling libc v0.2.42
   Compiling scopeguard v0.3.3
   Compiling xdg v2.1.0
   Compiling maplit v1.0.1
   Compiling lazy_static v0.2.11
   Compiling version_check v0.1.3
   Compiling void v1.0.2
   Compiling gcc v0.3.54
   Compiling typeable v0.1.2
   Compiling unicode-width v0.1.5
   Compiling bitflags v1.0.3
   Compiling yaml-rust v0.3.5
   Compiling linked-hash-map v0.5.1
   Compiling nix v0.11.0
   Compiling num-traits v0.2.5
   Compiling pkg-config v0.3.11
   Compiling dtoa v0.4.2
   Compiling utf8-ranges v1.0.0
   Compiling num-iter v0.1.37
   Compiling ansi_term v0.11.0
   Compiling language-tags v0.2.2
   Compiling snowflake v1.3.0
   Compiling rustc-demangle v0.1.8
   Compiling lazy_static v1.0.1
   Compiling serde v1.0.69
   Compiling percent-encoding v1.0.1
   Compiling httparse v1.3.2
   Compiling ucd-util v0.1.1
   Compiling traitobject v0.1.0
   Compiling termcolor v0.3.6
   Compiling humantime v1.1.1
   Compiling unicode-bidi v0.2.6
   Compiling unicode-bidi v0.3.4
   Compiling base64 v0.5.2
   Compiling arrayvec v0.4.7
   Compiling proc-macro2 v0.4.6
   Compiling serde_test v0.8.23
   Compiling synom v0.11.3
   Compiling backtrace-sys v0.1.23
   Compiling log v0.4.3
   Compiling crossbeam-utils v0.2.2
   Compiling base64 v0.6.0
   Compiling itertools v0.7.8
   Compiling kernel32-sys v0.2.2
   Compiling memchr v2.0.1
   Compiling rand v0.4.2
   Compiling memchr v0.1.11
   Compiling time v0.1.40
   Compiling atty v0.2.10
   Compiling num_cpus v1.8.0
   Compiling memchr v1.0.2
   Compiling unreachable v1.0.0
   Compiling unicase v2.1.0
   Compiling unicase v1.4.2
   Compiling textwrap v0.10.0
   Compiling yaml-rust v0.4.0
   Compiling fuse v0.3.1
   Compiling id_tree v1.3.0
   Compiling regex-syntax v0.6.1
   Compiling linked-hash-map v0.3.0
   Compiling idna v0.1.4
   Compiling syn v0.11.11
   Compiling log v0.3.9
   Compiling quote v0.6.3
   Compiling crossbeam-epoch v0.3.1
   Compiling aho-corasick v0.5.3
   Compiling aho-corasick v0.6.5
   Compiling nom v3.2.1
   Compiling rand v0.3.22
   Compiling thread_local v0.3.5
   Compiling clap v2.32.0
   Compiling mime v0.2.6
   Compiling syn v0.14.4
   Compiling crossbeam-deque v0.2.0
   Compiling synstructure v0.6.1
   Compiling uuid v0.2.3
   Compiling num-traits v0.1.43
   Compiling ctrlc v3.1.1
   Compiling serde_json v1.0.22
   Compiling toml v0.4.6
   Compiling url v1.7.0
   Compiling backtrace v0.3.9
   Compiling thread-id v2.0.0
   Compiling url v0.5.10
   Compiling mime v0.3.8
   Compiling failure_derive v0.1.1
   Compiling serde_derive v1.0.69
   Compiling chrono v0.4.4
   Compiling env_logger v0.5.10
   Compiling thread_local v0.2.7
   Compiling rayon v0.7.1
   Compiling hyper v0.10.13
   Compiling mime-sniffer v0.1.2
   Compiling failure v0.1.1
   Compiling num v0.1.42
   Compiling regex v0.1.80
   Compiling ring v0.11.0
   Compiling pretty_env_logger v0.2.3
   Compiling chrono v0.2.25
   Compiling serde-hjson v0.8.1
   Compiling config v0.8.0
   Compiling webpki v0.14.0
   Compiling webpki-roots v0.11.0
   Compiling rustls v0.9.0
   Compiling hyper-rustls v0.6.1
   Compiling yup-oauth2 v1.0.7
   Compiling google-drive3-fork v1.0.10
   Compiling gcsf v0.1.7
error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:275:13
    |
275 |             FileId::Inode(inode) => self.node_ids.contains_key(&inode),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::Inode(inode)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:276:13
    |
276 |             FileId::DriveId(drive_id) => self.drive_ids.contains_key(drive_id),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::DriveId(drive_id)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:277:13
    |
277 |             FileId::NodeId(node_id) => self.tree.get(&node_id).is_ok(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::NodeId(node_id)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:278:18
    |
278 |             pn @ FileId::ParentAndName { .. } => self.get_file(&pn).is_some(),
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::ParentAndName { .. }`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:284:13
    |
284 |             FileId::Inode(inode) => self.node_ids.get(&inode).cloned(),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::Inode(inode)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:285:13
    |
285 |             FileId::DriveId(drive_id) => self.get_node_id(&FileId::Inode(self.get_inode(
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::DriveId(drive_id)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:288:13
    |
288 |             FileId::NodeId(node_id) => Some(node_id.clone()),
    |             ^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::NodeId(node_id)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:289:22
    |
289 |             ref pn @ FileId::ParentAndName { .. } => {
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::ParentAndName { .. }`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:302:13
    |
302 |             FileId::Inode(inode) => Some(*inode),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::Inode(inode)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:303:13
    |
303 |             FileId::DriveId(drive_id) => self.drive_ids.get(drive_id).cloned(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::DriveId(drive_id)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:304:13
    |
304 |             FileId::NodeId(node_id) => self.tree
    |             ^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::NodeId(node_id)`
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:309:13
    |
309 | /             FileId::ParentAndName {
310 | |                 ref parent,
311 | |                 ref name,
312 | |             } => self.get_children(&FileId::Inode(*parent))?
    | |_____________^
    |
    = help: add #![feature(match_default_bindings)] to the crate attributes to enable
help: consider using a reference
    |
309 |             &FileId::ParentAndName {
310 |                 ref parent,
311 |                 ref name,
312 |             } => self.get_children(&FileId::Inode(*parent))?
    |

error: aborting due to 12 previous errors

error: failed to compile `gcsf v0.1.7`, intermediate artifacts can be found at `/tmp/cargo-install.KtxsptlZHLVq`

Caused by:
  Could not compile `gcsf`.

To learn more, run the command again with --verbose.

What logs/information could I provide to sort this out...really want to get this working. Thanks.

**Comment by harababurel** [comment]
Take a look at https://github.com/harababurel/gcsf/issues/12#issuecomment-401661486. Let me know if this fixes your issue.

**Comment by sharnal** [comment]
Yes I updated rust and cargo accordingly and have it setup. Thanks!
