### ISSUE TITLE
Failure - PayloadTooLarge

### ISSUE THREAD

**Issue by Deadolus** [harababurel/gcsf#23]
After authenticating with google I get following error. 
```

INFO  gcsf > Creating and populating file system...
 ERROR gcsf::gcsf::file_manager > Could not populate filesystem: Failure(
    Response {
        status: PayloadTooLarge,
        headers: Headers { Content-Type: text/html; charset=UTF-8
        , Referrer-Policy: no-referrer
        , Content-Length: 2398
        , Date: Tue, 03 Jul 2018 06:40:04 GMT
        , },
        version: Http10,
        url: "https://www.googleapis.com/drive/v3/files?spaces=drive&q=%28%271
...LONG_AND_POSSIBLY_SENSITIVE_URLS_...
&alt=json",
        status_raw: RawStatus(
            413,
            "Request Entity Too Large"
        ),
        message: Http11Message {
            is_proxied: false,
            method: None,
            stream: Wrapper {
                obj: Some(
                    Reading(
                        SizedReader(remaining=0)
                    )
                )
            }
        }
    }
)
 INFO  gcsf                     > File sytem created.
 INFO  gcsf                     > Mounting to /media/user/googledrive/
 INFO  gcsf                     > Mounted to /media/user/googledrive/
```

Possibly related to this: when I look in to the mounted directory it seems like all files up to the "first" level are there, but files in the second subdirectories are not: 

GOOGLEDRIVE/A/FILE1 is there   
GOOGLEDRIVE/A/B/FILE2 is missing

Note: I have a paid Googledrive subscription of 100GB, which is almost full.

**Comment by AndreiBarsan** [comment]
Amazing work on this project!

But, sadly, I also get this error when I try to mount. :( 
For what it's worth, I have *a lot* of stuff on my (now, nearly 10 year old) Drive... This includes weird stuff like some datasets which may have huge numbers of subdirectories, etc.

**Comment by harababurel** [comment]
I have changed the mount mechanism as of version 0.1.17 (ad5d8bbd6d55254eb94a056292e9872662bb65c5). The file system now requests all files at once (well, in chunks of as many as the API can provide) and rearrange them in the correct hierarchy afterwards. This should fix the `PayloadTooLarge` error and likely improve the mount time, unless you have a lot of files which are shared with you.

Consider giving this version a try and let me know if it improves your experience.

**Comment by Deadolus** [comment]
Thank you for looking in to this. 
Indeed I now no longer receive that error. 
You may underestimate the amount of stuff some people have on their Google drives (me included). 
I will create another ticket to describe my problem. 
Thank you very much for fixing this issue - keep up the good work.
