### ISSUE TITLE
non-reference pattern used to match a reference (see issue #42640)

### ISSUE THREAD

**Issue by isradelatorre** [harababurel/gcsf#30]
Hello there,
I'm having issues trying to install gcsf on Ubuntu 18.04. Some minutes after run _cargo install gcsf_ I'm getting error messages likes these:

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:302:13
    |
302 |             FileId::Inode(inode) => Some(*inode),
    |             ^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::Inode(inode)`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:303:13
    |
303 |             FileId::DriveId(drive_id) => self.drive_ids.get(drive_id).cloned(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::DriveId(drive_id)`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
   --> src/gcsf/file_manager.rs:304:13
    |
304 |             FileId::NodeId(node_id) => self.tree
    |             ^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&FileId::NodeId(node_id)`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)

`cargo -V
cargo 0.26.0`
`rustc -V
rustc 1.25.0`

Thanks in advance!

**Comment by harababurel** [comment]
This looks like #12. Try updating Rust to the latest version.

**Comment by isradelatorre** [comment]
Thanks Sergiu. After upgrade rust to latest version (1.27.2) I got another error:

error: failed to run custom build command for `openssl-sys v0.9.33`

Solved installing libssl-dev on Ubuntu 18.04

`sudo apt install libssl-dev`

Thanks!
