### ISSUE TITLE
ERR_CONNECTION_REFUSED on login after redirect from Google

### ISSUE THREAD

**Issue by jwallden** [harababurel/gcsf#41]
After authorizing gcsf and being redirected to http://localhost:8081 i get connection refused. I did
`netstat -tulpn | grep LISTEN` but couldn't see port 8081 being used. Is the server that is supposed to handle the redirect not started correctly?

**Comment by harababurel** [comment]
That's interesting, I have no idea why that would happen.
I updated the dependencies in version 0.1.18, try using this version and maybe the issue will fix itself. Will investigate further if it doesn't.

**Comment by jwallden** [comment]
Yeah, so this is somewhat embarrasing. I am remotely logged in to one of my machines where I wanted to mount my Google Drive. However, I hade the browser started on the local machine so no wonder it couldn't establish a connection to localhost... Everything works fine when using a browser started on the remote machine! :smile: 
Sorry for the inconvenience!

**Comment by harababurel** [comment]
No worries. You might want to look into setting `authorize_using_code = true` in your `~/.config/gcsf/gcsf.toml` file. This way, gcsf doesn't rely on a redirect to localhost anymore, but instead you have to copy and paste an authorization code between your local browser and the remote session.
