### ISSUE TITLE
user_allow_other in /etc/fuse.conf

### ISSUE THREAD

**Issue by bexelbie** [harababurel/gcsf#43]
What permissions are required that necessitate adding this option to /etc/fuse.conf?

Is this because allow_root is a default mount option?

**Comment by harababurel** [comment]
That is correct. You can remove `allow_root` from the `mount_options` and the file system can be mounted without requiring `user_allow_other` in `/etc/fuse.conf`. However in this case only the user who mounted the file system will have access to it. Any other user (including `root`) will be denied access, even though all files and directories are technically owned by `root`.
