### ISSUE TITLE
Authenticate on server with only Terminal

### ISSUE THREAD

**Issue by Nornode** [harababurel/gcsf#48]
I can't access a brower on the server I'm trying to authenticate.
Hence I have tried to copypaste the link:
`https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/drive&redirect_uri=http://localhost:8081&response_type=code&clien...`
to my desktop and pasting the answer starting with:
`code=4/yADuHTvSsLq2f_W_...`
In to a textfile as described: "$HOME/.config/gcsf/some_session_name"
However Mounting fails with:
` INFO  gcsf > Creating and populating file system...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Error("expected value", line: 1, column: 1) }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

How do you authenticate on a server that you don't have browser access to?
Else please give me an example file how the session name file should look like.
Thanks!

**Comment by foscone** [comment]
Should I reset authorize_using_code to false or can it remain set to true?

**Comment by harababurel** [comment]
Solved in #61, closing.
