### ISSUE TITLE
Automounting 

### ISSUE THREAD

**Issue by kcallis** [harababurel/gcsf#49]
Currently, I have to open up a terminal and start **gcsf** which stays in the foreground. I thought that I could write a script to test if there was internet connectivity and if so, _automount_ the google drive. That does not work, and I am still forces to manually start an instance. 

Am I doing something wrong with my script (I have also tried to use .zprofile as well, and it doesn't work either) or is this an issue native to using fuse?

**Comment by harababurel** [comment]
See https://github.com/harababurel/gcsf/issues/37#issuecomment-442092801.

tl;dr: you can use the included `gcsf.service` file to manage GCSF using systemd. I will implement #50 this weekend. This will cause GCSF to die in case of no network connectivity and then systemd can do its job of restarting the service automatically when it detects the abnormal death.
