### ISSUE TITLE
Error when i want to add an account

### ISSUE THREAD

**Issue by xxx31fr** [harababurel/gcsf#61]
Hello,
I try to add an account, but, I get an error as you can see on the screen

<img width="987" alt="error" src="https://user-images.githubusercontent.com/8737328/53019350-cfd12c00-3454-11e9-852c-68315187b425.png">

Thank you for your help

**Comment by foscone** [comment]
Hi, I have the same error when I try to add the first account whit `gcsf login` command.
Did you solve the problem?
Thanks

**Comment by foscone** [comment]
Sorry, i solved following this issue: https://github.com/harababurel/gcsf/issues/48
I was opening the link from a different computer.
