### ISSUE TITLE
Google Drive: Operation not permitted - fuse.conf problems

### ISSUE THREAD

**Issue by graves** [harababurel/gcsf#74]
After building the binary, moving it to debian server, and executing:

```
./gcsf mount Google\ Drive -s gdrive
```
I was receiving the following error:

fuse: failed to exec fusermount: No such file or directory
 ERROR gcsf > Could not mount to Google Drive: Operation not permitted (os error 1)

```
echo 'user_allow_other' > fuse.conf
chmod 644 fuse.conf
sudo chown root:root fuse.conf
sudo mv fuse.conf /etc
```
Fixes the problem.

Would anyone like this more explicit in the docs?

**Comment by harababurel** [comment]
Thanks for pointing this out, I updated the docs in 23f110763389ac862d4794d2eaf5861202838049.

**Comment by monomycelium** [comment]
Even after executing the commands, I get a similar error:
``` console
$ gcsf login home
Please direct your browser to https://accounts.google.com/o/oauth2/[...] and follow the instructions displayed there.
Successfully logged in. Saved credentials to "/home/fre/.config/gcsf/home"
$ mkdir ~/drive
$ gcsf mount ~/drive -s home
 INFO  fuser::session > Mounting /home/fre/drive
fuse: failed to exec fusermount: No such file or directory
 ERROR gcsf           > Could not mount to /home/fre/drive: Operation not permitted (os error 1)
```

I am running `GCSF 0.2.4` on Fedora 39.
